version: "2"

services:
  priva:
    build: ./deps/splatoon-privas
    volumes:
      - "./deps/splatoon-privas:/code"
    command: python /code/src/start_rpc.py
    ports:
      - 4242
  dev:
    build: .
    volumes:
      - ".:/code"
    depends_on:
      - priva
    command: npm run dev
    environment:
      - CQ_HOST=${CQ_HOST}
      - CQ_ACCESS_TOKEN=${CQ_ACCESS_TOKEN}
      - TSBOT_ADMIN=${TSBOT_ADMIN}
      - QQAI_APPID=${QQAI_APPID}
      - QQAI_APPKEY=${QQAI_APPKEY}
      - BOT_DEBUG=true
      - PRIVA_HOST=priva:4242
      - DISABLE_SHARE=${DISABLE_SHARE}
